### ISSUE TITLE
Mother, Father, Guardian input fields

### ISSUE THREAD

**Issue by jamccomb92** [hopetambala/puente-ionic-datacollection#53]
### Description
I am running Puente-ionic data collection on my local machine. I am able to log in and I then attempt to create an ID form (Identification and Registration). I am able to get to the form. Then I attempt to fill in the data. I am able to fill in everything but three fields:

<img width="938" alt="Screen Shot 2019-11-08 at 10 02 28 PM" src="https://user-images.githubusercontent.com/44590902/68521961-1c26fb00-0274-11ea-8407-78f40c4e2721.png">

<img width="945" alt="Screen Shot 2019-11-08 at 10 02 38 PM" src="https://user-images.githubusercontent.com/44590902/68521962-221cdc00-0274-11ea-80ff-be50e01f36bc.png">

Whenever I try to enter any values in the "Mother, Father, Guardian" First Name or Last name (as soon as I click the text box to enter the text, the site immediately goes to this page:

<img width="937" alt="Screen Shot 2019-11-08 at 10 09 52 PM" src="https://user-images.githubusercontent.com/44590902/68522002-7f189200-0274-11ea-8dbd-2497eb88b64e.png">

### Environment
- version of Puente-Ionic-Datacollection?
- which browser and its version? Chrome Version 77.0.3865.120
- versions of the following (if known and/or applicable)
  - node.js: 8.1.2
  - RxJS

### Steps to reproduce
Run MongoD in one terminal, run ionic serve inside of ionic data collection folder with node environment (8.1.2) in a second terminal, and npm start inside of Puente node cloud code folder with node environment (8.1.2) in a third terminal. Login to the Puente ionic data collection app (started with ionic serve) that opened in browser. Click on ID to fill out that form. Click in either the "Mother, Father, Guardian" first name or last name and the error should present itself.

### Expected results
I expected to be able to enter text into the fields.

### Actual results
I received an error message from Chrome (pictured above).

**Comment by hopetambala** [comment]
Great issue!

I've found the problematic code and I have changed this
```
<ion-item (click)="presentModal()">
          <ion-label stacked >{{'MOTHERFATHERGUARDIAN' | translate}}: </ion-label>
          <ion-input type="text" [(ngModel)]="relationship.fname" placeholder="{{ 'FIRSTNAME' | translate }}" disabled="disabled"></ion-input>
          <ion-input type="text" [(ngModel)]="relationship.lname" placeholder="{{ 'LASTNAME' | translate }}" disabled="disabled"></ion-input>
        </ion-item>
```

to this

```
<ion-item (click)="presentModal()">
          <ion-label stacked >{{'MOTHERFATHERGUARDIAN' | translate}}: </ion-label>
          <ion-input type="text" placeholder="{{ 'FIRSTNAME' | translate }}" disabled="disabled">{{relationship.fname}}</ion-input>
          <ion-input type="text" placeholder="{{ 'LASTNAME' | translate }}" disabled="disabled">{{relationship.lname}}</ion-input>
        </ion-item>
```

there was a problem with the [ngModel] where we were dynamically changing values that shouldn't have been

good find! I've fixed it in this pull request   #55 

you should be able to pull master and get the new fix after `npm run reinstall && ionic serve`
