### ISSUE TITLE
Submit error for ID form 

### ISSUE THREAD

**Issue by jamccomb92** [hopetambala/puente-ionic-datacollection#54]
### Description
When running Puente ionic data collection on my local machine. I log into the local application running in my browser. I try to complete an ID form for the app. I can not enter any input to Mother, Father, Guardian first/last name, but everything else has data. I then try to submit the form by pressing the "submit button" at the bottom of the page and receive this error.

<img width="945" alt="Screen Shot 2019-11-08 at 10 26 24 PM" src="https://user-images.githubusercontent.com/44590902/68522209-ce5fc200-0276-11ea-91ab-1f193b5e8b2b.png">

### Environment
- version of Puente-Ionic-Datacollection?
- which browser and its version? Chrome Version 77.0.3865.120
- versions of the following (if known and/or applicable)
  - node.js: 8.1.2
  - RxJS

### Steps to reproduce
Run Mongod in one terminal, run ionic serve inside of Puente ionic data collection with a node virtual environment in another terminal, run npm run start inside of Puente node cloud folder with node virtual environment in a third terminal. Login to Puente ionic data collection app in browser (started with ionic run serve). Click on the ID form. Fill out the form. Hit the submit button, This is where I see the error page shown above.

### Expected results
I expected to see some submission success confirmation page and then be able to use that patient information in other forms on the application.

### Actual results
I received the error message shown above.

**Comment by hopetambala** [comment]
Well written issue

_Mother, Father, Guardian first/last name_ is a field that pulls a list from previously submitted IDs so if you haven't been able to submit a survey yet, that's probably why you can't enter anything there

What seems to be the root problem is that your survey isn't able to get latitude/longitude coordinates. Before you tried to submit a survey, did you press that geolocation button?

**Comment by jamccomb92** [comment]
I tried to press the geolocation button prior to submitting, but it did not appear to do anything. I tried submitting the form without pressing the button and pressing the button and received the same error page.

**Comment by jamccomb92** [comment]
The issue was on my side. My browser was blocking location tracking. Thanks for the quick responses, issue has been resolved.
